# Generated by Django 4.1 on 2023-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-avg_rating',)},
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
