# Generated by Django 4.1 on 2023-03-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_options_product_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteshop',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='favoriteshop',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
