# Generated by Django 4.1.7 on 2023-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_alter_review_content_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
